# shopify.app.toml

client_id = "3200cefb971c73fc377f601e617ba66f"
name = "waitlist"
handle = "waitlist"
application_url = "https://shopify-waitlist-app.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# We need these permissions to save customers
scopes = "write_products,write_customers"

[auth]
redirect_urls = [
  "https://shopify-waitlist-app.onrender.com/auth/callback",
  "https://shopify-waitlist-app.onrender.com/auth/shopify/callback",
  "https://shopify-waitlist-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false